JavaScript Tracker YouTube Tracking (close #1014)
snowplow/snowplow-javascript-tracker pull request #1020
Opened 2021-12-10 20:05 UTC by greg-el

2021-12-10 20:05 UTC, snowplowcla commented
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

2021-12-22 16:53 UTC, paulboocock reviewed
Looking good! I have some more testing and verification of the data it produces that I want to do but my initial impressions are good. A few nitpicky comments dotted around to keep you busy until then :-)

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/helperFunctions.ts
> +export class UrlParameters {
I've typically avoided classes and gone for a more function based approach in the tracker. I think it'd be good to maintain that, I don't think classes add much besides some syntax sugar and they will be transpiled into a function anyway with (likely) some extra boilerplate code included.

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +export const _trackers: Record<string, BrowserTracker> = {};
nit: export hidden amongst other varaibles (and it's const with all the lets). Consider bumping to top of list.

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +  firstScriptTag.parentNode!.insertBefore(tag, firstScriptTag);
Do we need to include this, or could we document this is a required prerequiste? I quite like the idea of including it, I'm just wondering if we need to, does it make it much nicer to use if this is a tracker function vs expecting users to add it themselves?

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +    LOG.error('Cannot find YouTube IFrame element');
```suggestion
    LOG.error('Cannot find YouTube iframe');
```

Save a few bytes ;-)

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +  enableYouTubeIframeAPI();
Similar to my earlier comment, what if a user has already added this to their website? Maybe they use another tool that needs the API on their page. Would we end up loading it twice, with the later load not being required.

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +
In a similar vein to the above... This section seems important to get stuff set up... however, what is it's already loaded before the tracker loads (i.e. the script it already on the page), would `window.onYouTubeIframeAPIReady` even fire?

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +let tracked_players: Record<string, TrackedPlayer> = {};
```suggestion
const tracked_players: Record<string, TrackedPlayer> = {};
```

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +let trackingQueue: Array<TrackingOptions> = [];
```suggestion
const trackingQueue: Array<TrackingOptions> = [];
```

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +  let playerEvents: Record<string, Function> = {};
```suggestion
  const playerEvents: Record<string, Function> = {};
```

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +  for (let event of conf.youtubeEvents) {
```suggestion
  for (const event of conf.youtubeEvents) {
```

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +  let playerInstance = tracked_players[conf.mediaId];
```suggestion
  const playerInstance = tracked_players[conf.mediaId];
```

2021-12-22 16:53 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +    enableVolumeTracking(player, conf, eventData);
Lets get some brackets around these I think? I'm sort of surprised prettier didn't do this automatically?

2021-12-22 16:53 UTC, paulboocock commented on trackers/javascript-tracker/rollup.config.test.js
> +    ],
I imagine this might conflict with the release/3.2.0 branch now. Might want to rebase this branch on the release branch now.

2021-12-22 16:53 UTC, paulboocock commented on trackers/javascript-tracker/test/micro-config/iglu.json
> +        }
This can be removed now

2021-12-22 16:53 UTC, paulboocock commented on trackers/javascript-tracker/tracker.config.ts
> +  youtubeTracking: false,
This flag should be in `tracker.lite.config.ts` too, and set to `false`.

2021-12-23 11:54 UTC, greg-el commented on plugins/browser-plugin-youtube-tracking/src/buildYouTubeEvent.ts
> +  if (player.getAvailableQualityLevels().length) {
I'm mostly confident it couldn't be, but it makes more sense to use a falsey check anyway.

2022-01-04 14:30 UTC, paulboocock commented on plugins/browser-plugin-youtube-tracking/src/index.ts
> +export const _trackers: Record<string, BrowserTracker> = {};
Looking at this again, it shouldn't be exported at all.

2022-01-04 16:01 UTC, paulboocock requested changes
Bar the bug I've found, this LGTM. Will approve once thats fixed (and the tests are fixed, but I see you're working on that!)

2022-01-06 15:08 UTC, merged